apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Deep Insights
    console.openshift.io/plugins: '["gitops-plugin"]'
    containerImage: quay.io/redhat-developer/gitops-operator
    description: Enables teams to adopt GitOps principles for managing cluster configurations
      and application delivery across hybrid multi-cluster Kubernetes environments.
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "true"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operatorframework.io/cluster-monitoring: "true"
    operatorframework.io/suggested-namespace: openshift-gitops-operator
    operators.openshift.io/infrastructure-features: '["disconnected"]'
    repository: https://github.com/redhat-developer/gitops-operator
    support: Red Hat
  name: gitops-operator.v1.8.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: An AnalysisRun is an instantiation of an AnalysisTemplate. AnalysisRuns
        are like Jobs in that they eventually complete.
      displayName: AnalysisRun
      kind: AnalysisRun
      name: analysisruns.argoproj.io
      version: v1alpha1
    - description: An AnalysisTemplate is a template spec which defines how to perform
        a canary analysis, such as the metrics, its frequency, and the values which
        are considered successful or failed.
      displayName: AnalysisTemplate
      kind: AnalysisTemplate
      name: analysistemplates.argoproj.io
      version: v1alpha1
    - description: An Application is a group of Kubernetes resources as defined by
        a manifest.
      displayName: Application
      kind: Application
      name: applications.argoproj.io
      version: v1alpha1
    - description: ApplicationSet is the representation of an ApplicationSet controller
        deployment.
      displayName: ApplicationSet
      kind: ApplicationSet
      name: applicationsets.argoproj.io
      version: v1alpha1
    - description: An AppProject is a logical grouping of Argo CD Applications.
      displayName: AppProject
      kind: AppProject
      name: appprojects.argoproj.io
      version: v1alpha1
    - description: Argo CD is the representation of an Argo CD deployment.
      displayName: Argo CD
      kind: ArgoCD
      name: argocds.argoproj.io
      resources:
      - kind: ArgoCD
        name: ""
        version: v1beta1
      - kind: ConfigMap
        name: ""
        version: v1
      - kind: CronJob
        name: ""
        version: v1
      - kind: Deployment
        name: ""
        version: v1
      - kind: Ingress
        name: ""
        version: v1
      - kind: Job
        name: ""
        version: v1
      - kind: PersistentVolumeClaim
        name: ""
        version: v1
      - kind: Pod
        name: ""
        version: v1
      - kind: Prometheus
        name: ""
        version: v1
      - kind: ReplicaSet
        name: ""
        version: v1
      - kind: Route
        name: ""
        version: v1
      - kind: Secret
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      - kind: ServiceMonitor
        name: ""
        version: v1
      - kind: StatefulSet
        name: ""
        version: v1
      version: v1beta1
    - description: A ClusterAnalysisTemplate is like an AnalysisTemplate,but it is
        not limited to its namespace. It can be used by any Rollout throughout the
        cluster.
      displayName: ClusterAnalysisTemplate
      kind: ClusterAnalysisTemplate
      name: clusteranalysistemplates.argoproj.io
      version: v1alpha1
    - description: An Experiment is limited run of one or more ReplicaSets for the
        purposes of analysis. Experiments typically run for a pre-determined duration,
        but can also run indefinitely until stopped.
      displayName: Experiment
      kind: Experiment
      name: experiments.argoproj.io
      version: v1alpha1
    - description: NotificationsConfigurations contains the notification template
        used to generate notifications that notify users about important changes in
        the application state.
      displayName: NotificationsConfiguration
      kind: NotificationsConfiguration
      name: notificationsconfigurations.argoproj.io
      version: v1alpha1
    - description: A controller for managing Argo Rollouts
      displayName: RolloutManager
      kind: RolloutManager
      name: rolloutmanagers.argoproj.io
      version: v1alpha1
    - description: GitopsService is the Schema for the gitopsservices API
      displayName: Gitops Service
      kind: GitopsService
      name: gitopsservices.pipelines.openshift.io
      version: v1alpha1
  displayName: Red Hat OpenShift GitOps
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - devtools
  - gitops
  - pipelines
  maintainers:
  - email: shbose@redhat.com
    name: shoubhik
  maturity: alpha
  provider:
    name: Red Hat Inc
  relatedImages:
  - image: registry.redhat.io/openshift-gitops-1/gitops-rhel8-operator@sha256:b3b8e2e8a4ed592a029ac30fa39419744a7ff95e8d9e94e13c04219e755af553
    name: manager
  - image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:baa41441752d6d739065eda587b92402e209c67fbcdacf0a40559d37c9e978eb
    name: kube-rbac-proxy
  - image: registry.redhat.io/openshift-gitops-1/dex-rhel8@sha256:9a17cb3f6a43b574d27233bf6ca145d38aa38195bed33d29441c9dc38ff317a7
    name: argocd_dex_image
  - image: registry.redhat.io/rh-sso-7/sso76-openshift-rhel8@sha256:cf52b301f1c37c1de925bcf7e16005b0a3a1865645db29fd671d47db592da1e7
    name: argocd_keycloak_image
  - image: registry.redhat.io/openshift-gitops-1/gitops-rhel8@sha256:8ebdaf548ad61d312d851d9840c6d0f7d99cf15eedd1aab08715d0f37b0ea8e8
    name: backend_image
  - image: registry.redhat.io/openshift-gitops-1/argocd-rhel8@sha256:2c5be3fefcb6cbef4f8af0030a630981b7452cab9d7f14b19856b8e4ea8e638f
    name: argocd_image
  - image: registry.redhat.io/rhel9/redis-7@sha256:848f4298a9465dafb7ce9790e991bd8a11de2558e3a6685e1d7c4a6e0fc5f371
    name: argocd_redis_image
  - image: registry.redhat.io/openshift4/ose-haproxy-router@sha256:72817b62a55fb0f82f2908effc7bd3d20409fc60e9f228449d8f78eb390e22ac
    name: argocd_redis_ha_proxy_image
  - image: registry.redhat.io/openshift-gitops-1/console-plugin-rhel8@sha256:d7fae25f0fb79fc8d0abccc2fbd30c74d56b16b2582b4794d67da7b256add3e7
    name: gitops_console_plugin_image
  - image: registry.redhat.io/openshift-gitops-1/argocd-extensions-rhel8@sha256:64dc5e6ee93fe076829e758087a69691752cfd26fe340ec12ab953b38dac2558
    name: argocd_extension_image
  - image: registry.redhat.io/openshift-gitops-1/argo-rollouts-rhel8@sha256:86e8e3fd40ba52e85463a2280f42329786ce1d823327db49a866ace6297d43e9
    name: argo_rollouts_image
  - image: registry.redhat.io/openshift-gitops-1/must-gather-rhel8@sha256:86d0c9efdcbb9923a30cd21a6b0ba9f92accadf6a200de2f01e79880f6e236c8
    name: must_gather_image
  - image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:cd1003ba9e9f51e132729592921201c8cea8b020442d96e72c9975d423915d10
    name: kube_rbac_proxy_image
  replaces: gitops-operator.v1.7.3
  version: 1.8.0
